[package]
name = "word-recoverer"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39 = "2.0"
tiny-hderive = "0.3"
secp256k1 = "0.27"
sha3 = "0.10"
sha2 = "0.10"
hex = "0.4"
rayon = "1.8"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
